//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB_7B_WF.ContactsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneContact", Namespace="http://stasyan.by/")]
    [System.SerializableAttribute()]
    public partial class PhoneContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stasyan.by/", ConfigurationName="ContactsServiceReference.ContactsServiceSoap")]
    public interface ContactsServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetPhoneContactsResult from namespace http://stasyan.by/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://stasyan.by/GetPhoneContacts", ReplyAction="*")]
        LB_7B_WF.ContactsServiceReference.GetPhoneContactsResponse GetPhoneContacts(LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stasyan.by/GetPhoneContacts", ReplyAction="*")]
        System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.GetPhoneContactsResponse> GetPhoneContactsAsync(LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequest request);
        
        // CODEGEN: Generating message contract since element name phoneContact from namespace http://stasyan.by/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://stasyan.by/AddContact", ReplyAction="*")]
        LB_7B_WF.ContactsServiceReference.AddContactResponse AddContact(LB_7B_WF.ContactsServiceReference.AddContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stasyan.by/AddContact", ReplyAction="*")]
        System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.AddContactResponse> AddContactAsync(LB_7B_WF.ContactsServiceReference.AddContactRequest request);
        
        // CODEGEN: Generating message contract since element name phoneContact from namespace http://stasyan.by/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://stasyan.by/UpdateContact", ReplyAction="*")]
        LB_7B_WF.ContactsServiceReference.UpdateContactResponse UpdateContact(LB_7B_WF.ContactsServiceReference.UpdateContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stasyan.by/UpdateContact", ReplyAction="*")]
        System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.UpdateContactResponse> UpdateContactAsync(LB_7B_WF.ContactsServiceReference.UpdateContactRequest request);
        
        // CODEGEN: Generating message contract since element name RemoveContactResult from namespace http://stasyan.by/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://stasyan.by/RemoveContact", ReplyAction="*")]
        LB_7B_WF.ContactsServiceReference.RemoveContactResponse RemoveContact(LB_7B_WF.ContactsServiceReference.RemoveContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stasyan.by/RemoveContact", ReplyAction="*")]
        System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.RemoveContactResponse> RemoveContactAsync(LB_7B_WF.ContactsServiceReference.RemoveContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhoneContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhoneContacts", Namespace="http://stasyan.by/", Order=0)]
        public LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequestBody Body;
        
        public GetPhoneContactsRequest() {
        }
        
        public GetPhoneContactsRequest(LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPhoneContactsRequestBody {
        
        public GetPhoneContactsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhoneContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhoneContactsResponse", Namespace="http://stasyan.by/", Order=0)]
        public LB_7B_WF.ContactsServiceReference.GetPhoneContactsResponseBody Body;
        
        public GetPhoneContactsResponse() {
        }
        
        public GetPhoneContactsResponse(LB_7B_WF.ContactsServiceReference.GetPhoneContactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stasyan.by/")]
    public partial class GetPhoneContactsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LB_7B_WF.ContactsServiceReference.PhoneContact[] GetPhoneContactsResult;
        
        public GetPhoneContactsResponseBody() {
        }
        
        public GetPhoneContactsResponseBody(LB_7B_WF.ContactsServiceReference.PhoneContact[] GetPhoneContactsResult) {
            this.GetPhoneContactsResult = GetPhoneContactsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContact", Namespace="http://stasyan.by/", Order=0)]
        public LB_7B_WF.ContactsServiceReference.AddContactRequestBody Body;
        
        public AddContactRequest() {
        }
        
        public AddContactRequest(LB_7B_WF.ContactsServiceReference.AddContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stasyan.by/")]
    public partial class AddContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LB_7B_WF.ContactsServiceReference.PhoneContact phoneContact;
        
        public AddContactRequestBody() {
        }
        
        public AddContactRequestBody(LB_7B_WF.ContactsServiceReference.PhoneContact phoneContact) {
            this.phoneContact = phoneContact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContactResponse", Namespace="http://stasyan.by/", Order=0)]
        public LB_7B_WF.ContactsServiceReference.AddContactResponseBody Body;
        
        public AddContactResponse() {
        }
        
        public AddContactResponse(LB_7B_WF.ContactsServiceReference.AddContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stasyan.by/")]
    public partial class AddContactResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LB_7B_WF.ContactsServiceReference.PhoneContact[] AddContactResult;
        
        public AddContactResponseBody() {
        }
        
        public AddContactResponseBody(LB_7B_WF.ContactsServiceReference.PhoneContact[] AddContactResult) {
            this.AddContactResult = AddContactResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContact", Namespace="http://stasyan.by/", Order=0)]
        public LB_7B_WF.ContactsServiceReference.UpdateContactRequestBody Body;
        
        public UpdateContactRequest() {
        }
        
        public UpdateContactRequest(LB_7B_WF.ContactsServiceReference.UpdateContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stasyan.by/")]
    public partial class UpdateContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LB_7B_WF.ContactsServiceReference.PhoneContact phoneContact;
        
        public UpdateContactRequestBody() {
        }
        
        public UpdateContactRequestBody(LB_7B_WF.ContactsServiceReference.PhoneContact phoneContact) {
            this.phoneContact = phoneContact;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateContactResponse", Namespace="http://stasyan.by/", Order=0)]
        public LB_7B_WF.ContactsServiceReference.UpdateContactResponseBody Body;
        
        public UpdateContactResponse() {
        }
        
        public UpdateContactResponse(LB_7B_WF.ContactsServiceReference.UpdateContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stasyan.by/")]
    public partial class UpdateContactResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LB_7B_WF.ContactsServiceReference.PhoneContact[] UpdateContactResult;
        
        public UpdateContactResponseBody() {
        }
        
        public UpdateContactResponseBody(LB_7B_WF.ContactsServiceReference.PhoneContact[] UpdateContactResult) {
            this.UpdateContactResult = UpdateContactResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContact", Namespace="http://stasyan.by/", Order=0)]
        public LB_7B_WF.ContactsServiceReference.RemoveContactRequestBody Body;
        
        public RemoveContactRequest() {
        }
        
        public RemoveContactRequest(LB_7B_WF.ContactsServiceReference.RemoveContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stasyan.by/")]
    public partial class RemoveContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public RemoveContactRequestBody() {
        }
        
        public RemoveContactRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContactResponse", Namespace="http://stasyan.by/", Order=0)]
        public LB_7B_WF.ContactsServiceReference.RemoveContactResponseBody Body;
        
        public RemoveContactResponse() {
        }
        
        public RemoveContactResponse(LB_7B_WF.ContactsServiceReference.RemoveContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://stasyan.by/")]
    public partial class RemoveContactResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LB_7B_WF.ContactsServiceReference.PhoneContact[] RemoveContactResult;
        
        public RemoveContactResponseBody() {
        }
        
        public RemoveContactResponseBody(LB_7B_WF.ContactsServiceReference.PhoneContact[] RemoveContactResult) {
            this.RemoveContactResult = RemoveContactResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContactsServiceSoapChannel : LB_7B_WF.ContactsServiceReference.ContactsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactsServiceSoapClient : System.ServiceModel.ClientBase<LB_7B_WF.ContactsServiceReference.ContactsServiceSoap>, LB_7B_WF.ContactsServiceReference.ContactsServiceSoap {
        
        public ContactsServiceSoapClient() {
        }
        
        public ContactsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LB_7B_WF.ContactsServiceReference.GetPhoneContactsResponse LB_7B_WF.ContactsServiceReference.ContactsServiceSoap.GetPhoneContacts(LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequest request) {
            return base.Channel.GetPhoneContacts(request);
        }
        
        public LB_7B_WF.ContactsServiceReference.PhoneContact[] GetPhoneContacts() {
            LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequest inValue = new LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequest();
            inValue.Body = new LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequestBody();
            LB_7B_WF.ContactsServiceReference.GetPhoneContactsResponse retVal = ((LB_7B_WF.ContactsServiceReference.ContactsServiceSoap)(this)).GetPhoneContacts(inValue);
            return retVal.Body.GetPhoneContactsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.GetPhoneContactsResponse> LB_7B_WF.ContactsServiceReference.ContactsServiceSoap.GetPhoneContactsAsync(LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequest request) {
            return base.Channel.GetPhoneContactsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.GetPhoneContactsResponse> GetPhoneContactsAsync() {
            LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequest inValue = new LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequest();
            inValue.Body = new LB_7B_WF.ContactsServiceReference.GetPhoneContactsRequestBody();
            return ((LB_7B_WF.ContactsServiceReference.ContactsServiceSoap)(this)).GetPhoneContactsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LB_7B_WF.ContactsServiceReference.AddContactResponse LB_7B_WF.ContactsServiceReference.ContactsServiceSoap.AddContact(LB_7B_WF.ContactsServiceReference.AddContactRequest request) {
            return base.Channel.AddContact(request);
        }
        
        public LB_7B_WF.ContactsServiceReference.PhoneContact[] AddContact(LB_7B_WF.ContactsServiceReference.PhoneContact phoneContact) {
            LB_7B_WF.ContactsServiceReference.AddContactRequest inValue = new LB_7B_WF.ContactsServiceReference.AddContactRequest();
            inValue.Body = new LB_7B_WF.ContactsServiceReference.AddContactRequestBody();
            inValue.Body.phoneContact = phoneContact;
            LB_7B_WF.ContactsServiceReference.AddContactResponse retVal = ((LB_7B_WF.ContactsServiceReference.ContactsServiceSoap)(this)).AddContact(inValue);
            return retVal.Body.AddContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.AddContactResponse> LB_7B_WF.ContactsServiceReference.ContactsServiceSoap.AddContactAsync(LB_7B_WF.ContactsServiceReference.AddContactRequest request) {
            return base.Channel.AddContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.AddContactResponse> AddContactAsync(LB_7B_WF.ContactsServiceReference.PhoneContact phoneContact) {
            LB_7B_WF.ContactsServiceReference.AddContactRequest inValue = new LB_7B_WF.ContactsServiceReference.AddContactRequest();
            inValue.Body = new LB_7B_WF.ContactsServiceReference.AddContactRequestBody();
            inValue.Body.phoneContact = phoneContact;
            return ((LB_7B_WF.ContactsServiceReference.ContactsServiceSoap)(this)).AddContactAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LB_7B_WF.ContactsServiceReference.UpdateContactResponse LB_7B_WF.ContactsServiceReference.ContactsServiceSoap.UpdateContact(LB_7B_WF.ContactsServiceReference.UpdateContactRequest request) {
            return base.Channel.UpdateContact(request);
        }
        
        public LB_7B_WF.ContactsServiceReference.PhoneContact[] UpdateContact(LB_7B_WF.ContactsServiceReference.PhoneContact phoneContact) {
            LB_7B_WF.ContactsServiceReference.UpdateContactRequest inValue = new LB_7B_WF.ContactsServiceReference.UpdateContactRequest();
            inValue.Body = new LB_7B_WF.ContactsServiceReference.UpdateContactRequestBody();
            inValue.Body.phoneContact = phoneContact;
            LB_7B_WF.ContactsServiceReference.UpdateContactResponse retVal = ((LB_7B_WF.ContactsServiceReference.ContactsServiceSoap)(this)).UpdateContact(inValue);
            return retVal.Body.UpdateContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.UpdateContactResponse> LB_7B_WF.ContactsServiceReference.ContactsServiceSoap.UpdateContactAsync(LB_7B_WF.ContactsServiceReference.UpdateContactRequest request) {
            return base.Channel.UpdateContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.UpdateContactResponse> UpdateContactAsync(LB_7B_WF.ContactsServiceReference.PhoneContact phoneContact) {
            LB_7B_WF.ContactsServiceReference.UpdateContactRequest inValue = new LB_7B_WF.ContactsServiceReference.UpdateContactRequest();
            inValue.Body = new LB_7B_WF.ContactsServiceReference.UpdateContactRequestBody();
            inValue.Body.phoneContact = phoneContact;
            return ((LB_7B_WF.ContactsServiceReference.ContactsServiceSoap)(this)).UpdateContactAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LB_7B_WF.ContactsServiceReference.RemoveContactResponse LB_7B_WF.ContactsServiceReference.ContactsServiceSoap.RemoveContact(LB_7B_WF.ContactsServiceReference.RemoveContactRequest request) {
            return base.Channel.RemoveContact(request);
        }
        
        public LB_7B_WF.ContactsServiceReference.PhoneContact[] RemoveContact(int id) {
            LB_7B_WF.ContactsServiceReference.RemoveContactRequest inValue = new LB_7B_WF.ContactsServiceReference.RemoveContactRequest();
            inValue.Body = new LB_7B_WF.ContactsServiceReference.RemoveContactRequestBody();
            inValue.Body.id = id;
            LB_7B_WF.ContactsServiceReference.RemoveContactResponse retVal = ((LB_7B_WF.ContactsServiceReference.ContactsServiceSoap)(this)).RemoveContact(inValue);
            return retVal.Body.RemoveContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.RemoveContactResponse> LB_7B_WF.ContactsServiceReference.ContactsServiceSoap.RemoveContactAsync(LB_7B_WF.ContactsServiceReference.RemoveContactRequest request) {
            return base.Channel.RemoveContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<LB_7B_WF.ContactsServiceReference.RemoveContactResponse> RemoveContactAsync(int id) {
            LB_7B_WF.ContactsServiceReference.RemoveContactRequest inValue = new LB_7B_WF.ContactsServiceReference.RemoveContactRequest();
            inValue.Body = new LB_7B_WF.ContactsServiceReference.RemoveContactRequestBody();
            inValue.Body.id = id;
            return ((LB_7B_WF.ContactsServiceReference.ContactsServiceSoap)(this)).RemoveContactAsync(inValue);
        }
    }
}
