//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB_7B_WF.WCFContactsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneContact", Namespace="http://schemas.datacontract.org/2004/07/LB_7C.Model")]
    [System.SerializableAttribute()]
    public partial class PhoneContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFContactsServiceReference.IPhoneContactService")]
    public interface IPhoneContactService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneContactService/GetPhoneContacts", ReplyAction="http://tempuri.org/IPhoneContactService/GetPhoneContactsResponse")]
        LB_7B_WF.WCFContactsServiceReference.PhoneContact[] GetPhoneContacts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneContactService/GetPhoneContacts", ReplyAction="http://tempuri.org/IPhoneContactService/GetPhoneContactsResponse")]
        System.Threading.Tasks.Task<LB_7B_WF.WCFContactsServiceReference.PhoneContact[]> GetPhoneContactsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneContactService/AddPhoneContact", ReplyAction="http://tempuri.org/IPhoneContactService/AddPhoneContactResponse")]
        LB_7B_WF.WCFContactsServiceReference.PhoneContact[] AddPhoneContact(LB_7B_WF.WCFContactsServiceReference.PhoneContact phoneContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneContactService/AddPhoneContact", ReplyAction="http://tempuri.org/IPhoneContactService/AddPhoneContactResponse")]
        System.Threading.Tasks.Task<LB_7B_WF.WCFContactsServiceReference.PhoneContact[]> AddPhoneContactAsync(LB_7B_WF.WCFContactsServiceReference.PhoneContact phoneContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneContactService/UpdatePhoneContact", ReplyAction="http://tempuri.org/IPhoneContactService/UpdatePhoneContactResponse")]
        LB_7B_WF.WCFContactsServiceReference.PhoneContact[] UpdatePhoneContact(LB_7B_WF.WCFContactsServiceReference.PhoneContact phoneContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneContactService/UpdatePhoneContact", ReplyAction="http://tempuri.org/IPhoneContactService/UpdatePhoneContactResponse")]
        System.Threading.Tasks.Task<LB_7B_WF.WCFContactsServiceReference.PhoneContact[]> UpdatePhoneContactAsync(LB_7B_WF.WCFContactsServiceReference.PhoneContact phoneContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneContactService/RemovePhoneContact", ReplyAction="http://tempuri.org/IPhoneContactService/RemovePhoneContactResponse")]
        LB_7B_WF.WCFContactsServiceReference.PhoneContact[] RemovePhoneContact(int phoneContactId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneContactService/RemovePhoneContact", ReplyAction="http://tempuri.org/IPhoneContactService/RemovePhoneContactResponse")]
        System.Threading.Tasks.Task<LB_7B_WF.WCFContactsServiceReference.PhoneContact[]> RemovePhoneContactAsync(int phoneContactId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneContactServiceChannel : LB_7B_WF.WCFContactsServiceReference.IPhoneContactService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneContactServiceClient : System.ServiceModel.ClientBase<LB_7B_WF.WCFContactsServiceReference.IPhoneContactService>, LB_7B_WF.WCFContactsServiceReference.IPhoneContactService {
        
        public PhoneContactServiceClient() {
        }
        
        public PhoneContactServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneContactServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneContactServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneContactServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LB_7B_WF.WCFContactsServiceReference.PhoneContact[] GetPhoneContacts() {
            return base.Channel.GetPhoneContacts();
        }
        
        public System.Threading.Tasks.Task<LB_7B_WF.WCFContactsServiceReference.PhoneContact[]> GetPhoneContactsAsync() {
            return base.Channel.GetPhoneContactsAsync();
        }
        
        public LB_7B_WF.WCFContactsServiceReference.PhoneContact[] AddPhoneContact(LB_7B_WF.WCFContactsServiceReference.PhoneContact phoneContact) {
            return base.Channel.AddPhoneContact(phoneContact);
        }
        
        public System.Threading.Tasks.Task<LB_7B_WF.WCFContactsServiceReference.PhoneContact[]> AddPhoneContactAsync(LB_7B_WF.WCFContactsServiceReference.PhoneContact phoneContact) {
            return base.Channel.AddPhoneContactAsync(phoneContact);
        }
        
        public LB_7B_WF.WCFContactsServiceReference.PhoneContact[] UpdatePhoneContact(LB_7B_WF.WCFContactsServiceReference.PhoneContact phoneContact) {
            return base.Channel.UpdatePhoneContact(phoneContact);
        }
        
        public System.Threading.Tasks.Task<LB_7B_WF.WCFContactsServiceReference.PhoneContact[]> UpdatePhoneContactAsync(LB_7B_WF.WCFContactsServiceReference.PhoneContact phoneContact) {
            return base.Channel.UpdatePhoneContactAsync(phoneContact);
        }
        
        public LB_7B_WF.WCFContactsServiceReference.PhoneContact[] RemovePhoneContact(int phoneContactId) {
            return base.Channel.RemovePhoneContact(phoneContactId);
        }
        
        public System.Threading.Tasks.Task<LB_7B_WF.WCFContactsServiceReference.PhoneContact[]> RemovePhoneContactAsync(int phoneContactId) {
            return base.Channel.RemovePhoneContactAsync(phoneContactId);
        }
    }
}
